// Code generated by MockGen. DO NOT EDIT.
// Source: ./redirecturl.go

// Package mock is a generated GoMock package.
package mock

import (
	errorx "URLShortener/common/errorx"
	po "URLShortener/model/po"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIRedirectURLRepo is a mock of IRedirectURLRepo interface.
type MockIRedirectURLRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIRedirectURLRepoMockRecorder
}

// MockIRedirectURLRepoMockRecorder is the mock recorder for MockIRedirectURLRepo.
type MockIRedirectURLRepoMockRecorder struct {
	mock *MockIRedirectURLRepo
}

// NewMockIRedirectURLRepo creates a new mock instance.
func NewMockIRedirectURLRepo(ctrl *gomock.Controller) *MockIRedirectURLRepo {
	mock := &MockIRedirectURLRepo{ctrl: ctrl}
	mock.recorder = &MockIRedirectURLRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRedirectURLRepo) EXPECT() *MockIRedirectURLRepoMockRecorder {
	return m.recorder
}

// GetOriginURL mocks base method.
func (m *MockIRedirectURLRepo) GetOriginURL(ctx context.Context, poReq *po.RedirectURLRequest) (*po.RedirectURLResponse, *errorx.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOriginURL", ctx, poReq)
	ret0, _ := ret[0].(*po.RedirectURLResponse)
	ret1, _ := ret[1].(*errorx.ServiceError)
	return ret0, ret1
}

// GetOriginURL indicates an expected call of GetOriginURL.
func (mr *MockIRedirectURLRepoMockRecorder) GetOriginURL(ctx, poReq interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginURL", reflect.TypeOf((*MockIRedirectURLRepo)(nil).GetOriginURL), ctx, poReq)
}
