// Code generated by MockGen. DO NOT EDIT.
// Source: ./urlshortener.go

// Package mock is a generated GoMock package.
package mock

import (
	errorx "URLShortener/common/errorx"
	po "URLShortener/model/po"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIURLShortenerRepo is a mock of IURLShortenerRepo interface.
type MockIURLShortenerRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIURLShortenerRepoMockRecorder
}

// MockIURLShortenerRepoMockRecorder is the mock recorder for MockIURLShortenerRepo.
type MockIURLShortenerRepoMockRecorder struct {
	mock *MockIURLShortenerRepo
}

// NewMockIURLShortenerRepo creates a new mock instance.
func NewMockIURLShortenerRepo(ctrl *gomock.Controller) *MockIURLShortenerRepo {
	mock := &MockIURLShortenerRepo{ctrl: ctrl}
	mock.recorder = &MockIURLShortenerRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIURLShortenerRepo) EXPECT() *MockIURLShortenerRepoMockRecorder {
	return m.recorder
}

// CreateShortenURL mocks base method.
func (m *MockIURLShortenerRepo) CreateShortenURL(ctx context.Context, poReq *po.CreateShortenURLRequest) (*po.CreateShortenURLResponse, *errorx.ServiceError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShortenURL", ctx, poReq)
	ret0, _ := ret[0].(*po.CreateShortenURLResponse)
	ret1, _ := ret[1].(*errorx.ServiceError)
	return ret0, ret1
}

// CreateShortenURL indicates an expected call of CreateShortenURL.
func (mr *MockIURLShortenerRepoMockRecorder) CreateShortenURL(ctx, poReq interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShortenURL", reflect.TypeOf((*MockIURLShortenerRepo)(nil).CreateShortenURL), ctx, poReq)
}
